### ISSUE TITLE
Error on web build 

### ISSUE THREAD

**Issue by guystyles** [gregmoser/muracon2016#1]
I got this error following your instructions while using os x 10.10.5
```
Status: Downloaded newer image for mysql:latest
Building web
Step 1 : FROM lucee/lucee-tomcat:4.5.1
Pulling repository docker.io/lucee/lucee-tomcat
ERROR: Service 'web' failed to build: Error: image lucee/lucee-tomcat:4.5.1 not found
```
404, or maybe its an operator error?

**Comment by gregmoser** [comment]
This repository is using an older build of Lucee that it looks like they don't support anymore on docker hub.  I'm putting together a new repository for MuraCon 2017 if you can wait :)

**Comment by guystyles** [comment]
How embarrassing it would have been to try and build this at MuraCon 2017.
Seems like you should dig up a copy of lucee-tomcat for archival purposes.
You never know who might need it.
Thank you, I am in no hurry.

**Comment by gregmoser** [comment]
I actually went ahead and updated this repo so it should build now.
